## STA 556 — Homework 1

### Part 1 — Inspect the data

In [1]:
import pandas as pd

In [2]:
students = pd.read_csv('../Data/Raw/students.csv')
enrollments = pd.read_csv('../Data/Raw/enrollments.csv')
courses = pd.read_csv('../Data/Raw/courses.csv')

In [3]:
students

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
1,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah
2,S1003,Noah,Garcia,Mathematics,1st,18.0,Yes,Spring 2024,2.81,18,Dr. Reed
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim
4,S1005,Ethan,Kim,Computer Science,4th,19.0,Yes,Spring 2025,NaN,18,Dr. Kim
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno
6,S1007,Olivia,Brown,Statistics,2nd,22.0,No,Spring 2026,3.75,36,Dr. Kim
7,S1008,Lucas,Wilson,Data Science,4th,27.0,Yes,Spring 2024,2.89,45,Dr. Shah
8,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45,Dr. Moreno
9,S1010,Mateo,Davis,Data Science,4th,27.0,Yes,Fall 2023,2.59,24,Dr. Reed
10,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54,Dr. Reed
11,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72,Dr. Reed
12,S1013,Amara,Taylor,Data Science,4th,NaN,Yes,Spring 2024,2.77,108,Dr. Kim
13,S1014,Henry,Anderson,Mathematics,1st,20.0,Yes,Spring 2025,2.66,45,Dr. Shah
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno
16,S1017,Nora,Lewis,Mathematics,2nd,19.0,Yes,Spring 2025,2.88,96,Dr. Moreno
17,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36,Dr. Kim
18,S1019,Zoe,Allen,Statistics,4th,18.0,No,Spring 2025,3.30,18,Dr. Shah
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
20,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30,Dr. Shah
21,S1022,Julian,Wright,Statistics,3rd,19.0,Yes,Spring 2025,NaN,18,Dr. Shah
22,S1023,Grace,Scott,Data Science,1st,19.0,Yes,Fall 2023,2.49,45,Dr. Moreno
23,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45,Dr. Kim
24,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,Dr. Moreno
25,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36,NaN
26,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36,Dr. Kim
27,S1028,Caleb,Hill,Mathematics,1st,20.0,No,Spring 2026,3.79,108,Dr. Reed
28,S1029,Aria,Campbell,Data Science,2nd,NaN,Yes,Spring 2025,2.58,54,Dr. Moreno
29,S1030,Miles,Mitchell,Computer Science,4th,22.0,Yes,Fall 2024,NaN,36,Dr. Kim

In [4]:
enrollments

,enrollment_id,student_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct
0,E5001,S1001,C102,Spring 2026,Completed,96,65.0,65.0,94.7
1,E5002,S1001,C106,Spring 2026,Completed,81,80.0,63.0,96.6
2,E5003,S1001,C103,Spring 2026,Completed,77,67.0,72.0,88.6
3,E5004,S1002,C106,Fall 2025,Completed,86,NaN,85.0,77.3
4,E5005,S1002,C101,Fall 2025,Completed,90,55.0,79.0,85.8
5,E5006,S1003,C102,Fall 2026,Enrolled,93,76.0,95.0,88.4
6,E5007,S1004,C105,Spring 2026,Completed,98,73.0,88.0,89.5
7,E5008,S1004,C101,Fall 2025,Completed,87,58.0,NaN,75.6
8,E5009,S1004,C104,Fall 2026,Enrolled,93,79.0,73.0,92.3
9,E5010,S1005,C101,Spring 2026,Completed,73,57.0,99.0,82.9
10,E5011,S1005,C108,Fall 2025,Completed,68,55.0,82.0,91.0
11,E5012,S1006,C105,Fall 2026,Enrolled,75,NaN,68.0,97.2
12,E5013,S1006,C101,Fall 2026,Enrolled,98,81.0,82.0,80.0
13,E5014,S1007,C103,Fall 2025,Completed,61,93.0,86.0,85.8
14,E5015,S1007,C106,Spring 2026,Completed,59,82.0,60.0,96.9
15,E5016,S1008,C104,Spring 2026,Completed,83,83.0,78.0,85.8
16,E5017,S1008,C102,Fall 2025,Completed,89,65.0,79.0,NaN
17,E5018,S1008,C101,Spring 2026,Completed,74,70.0,62.0,87.4
18,E5019,S1009,C103,Fall 2026,Enrolled,84,61.0,81.0,74.4
19,E5020,S1009,C108,Spring 2026,Completed,73,NaN,71.0,84.2
20,E5021,S1010,C102,Fall 2026,Enrolled,74,97.0,81.0,79.5
21,E5022,S1010,C108,Fall 2026,Enrolled,66,70.0,100.0,72.1
22,E5023,S1011,C108,Fall 2026,Enrolled,61,59.0,79.0,94.4
23,E5024,S1012,C108,Fall 2026,Enrolled,66,76.0,66.0,78.0
24,E5025,S1013,C108,Fall 2025,Completed,83,70.0,NaN,91.2
25,E5026,S1013,C104,Fall 2026,Enrolled,68,78.0,77.0,81.7
26,E5027,S1014,C102,Fall 2025,Completed,71,62.0,61.0,82.3
27,E5028,S1014,C101,Fall 2025,Completed,88,NaN,77.0,77.6
28,E5029,S1015,C105,Fall 2026,Enrolled,61,96.0,88.0,82.3
29,E5030,S1016,C106,Fall 2026,Enrolled,79,98.0,96.0,79.1
30,E5031,S1016,C101,Fall 2025,Completed,76,64.0,99.0,89.7
31,E5032,S1016,C102,Spring 2026,Completed,75,89.0,75.0,74.4
32,E5033,S1017,C102,Fall 2025,Completed,70,97.0,87.0,96.9
33,E5034,S1017,C107,Spring 2026,Completed,61,70.0,86.0,NaN
34,E5035,S1018,C108,Fall 2026,Enrolled,74,87.0,64.0,99.8
35,E5036,S1018,C107,Fall 2026,Enrolled,61,64.0,93.0,73.7
36,E5037,S1018,C105,Spring 2026,Completed,58,NaN,65.0,95.9
37,E5038,S1019,C104,Fall 2025,Completed,77,62.0,97.0,74.1
38,E5039,S1019,C103,Fall 2026,Enrolled,61,77.0,95.0,96.1
39,E5040,S1020,C103,Fall 2025,Completed,91,61.0,73.0,97.6
40,E5041,S1020,C102,Spring 2026,Completed,67,56.0,76.0,80.4
41,E5042,S1021,C107,Fall 2025,Completed,89,68.0,NaN,73.9
42,E5043,S1021,C101,Fall 2026,Enrolled,79,92.0,71.0,91.9
43,E5044,S1022,C107,Fall 2025,Completed,76,74.0,72.0,92.6
44,E5045,S1022,C102,Spring 2026,Completed,62,61.0,71.0,85.2
45,E5046,S1023,C102,Fall 2025,Completed,98,84.0,86.0,80.6
46,E5047,S1023,C106,Spring 2026,Completed,70,74.0,98.0,77.8
47,E5048,S1024,C106,Fall 2026,Enrolled,77,85.0,66.0,73.0
48,E5049,S1024,C101,Spring 2026,Completed,77,84.0,82.0,83.5
49,E5050,S1025,C102,Fall 2025,Completed,80,79.0,64.0,79.7
50,E5051,S1025,C106,Fall 2025,Completed,92,58.0,75.0,87.6
51,E5052,S1026,C104,Fall 2026,Enrolled,70,63.0,68.0,90.7
52,E5053,S1027,C107,Fall 2026,Enrolled,87,64.0,94.0,77.3
53,E5054,S1028,C107,Fall 2025,Completed,85,98.0,88.0,72.1
54,E5055,S1028,C105,Spring 2026,Completed,73,95.0,85.0,91.9
55,E5056,S1029,C104,Spring 2026,Completed,88,57.0,85.0,80.3
56,E5057,S1029,C108,Fall 2026,Enrolled,73,62.0,78.0,94.2
57,E5058,S9999,C106,Fall 2026,Enrolled,84,88.0,91.0,94.0
58,E5059,S1008,C999,Fall 2026,Enrolled,79,82.0,86.0,89.0

In [5]:
courses

,course_id,department,course_number,course_title,credits,level,delivery
0,C101,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person
1,C102,STA,270,Applied Statistics,3,Undergraduate,Hybrid
2,C103,CS,126,Introduction to Computing,4,Undergraduate,In Person
3,C104,MAT,239,Linear Algebra,3,Undergraduate,In Person
4,C105,STA,444,Statistical Computing,3,Undergraduate,Online
5,C106,STA,556,Statistics and Data Science Computing Workflows,3,Graduate,In Person
6,C107,CS,345,Databases,3,Undergraduate,Online
7,C108,MAT,442,Probability,3,Undergraduate,Hybrid

In [6]:
print(students.shape)
print(enrollments.shape)
print(courses.shape)

(30, 11)
(59, 9)
(8, 7)

In [7]:
print(students.dtypes)
print(enrollments.dtypes)
print(courses.dtypes)

student_id               str
first_name               str
last_name                str
program                  str
year                     str
age                  float64
active                   str
entry_term               str
gpa                  float64
credits_completed      int64
advisor                  str
dtype: object
enrollment_id         str
student_id            str
course_id             str
term                  str
status                str
midterm_score       int64
final_score       float64
project_score     float64
attendance_pct    float64
dtype: object
course_id          str
department         str
course_number    int64
course_title       str
credits          int64
level              str
delivery           str
dtype: object

In [21]:
print(students.isnull().sum())
print(enrollments.isnull().sum())
print(courses.isnull().sum())

student_id           0
first_name           0
last_name            0
program              0
year                 0
age                  2
active               0
entry_term           0
gpa                  3
credits_completed    0
advisor              1
dtype: int64
enrollment_id     0
student_id        0
course_id         0
term              0
status            0
midterm_score     0
final_score       5
project_score     3
attendance_pct    2
dtype: int64
course_id        0
department       0
course_number    0
course_title     0
credits          0
level            0
delivery         0
dtype: int64

While inspecting the data sets I noticed the students table contains missing values across multiple columns, specifically there is 2 missing entries in age, 3 in gpa, and 1 in advisor. Also, the enrollments table has missing entries like 5 missing from final_score, 3 missing from project_score, and 2 missing from attendance_pct. The courses table didn't have any missing data but the other missing entries should be be addressed prior to working with the data to prevent unintended data loss or skew.

### Part 2 — Filtering and derived variables

In [85]:
students_2 = students.loc[
    (students['active'] == 'Yes') & (students['gpa'] >= 3.00)
].copy()
students_2

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno
8,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45,Dr. Moreno
10,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54,Dr. Reed
11,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72,Dr. Reed
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno
17,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36,Dr. Kim
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah
20,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30,Dr. Shah
23,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45,Dr. Kim
24,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,Dr. Moreno
25,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36,NaN
26,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36,Dr. Kim

In [86]:
entry = students_2['entry_term'].str.extract(r'(\d{4})')[0].astype(int)
students_2['years_in_college'] = (2026 - entry).apply(lambda x: max(1, x))

students_2['credits_per_year'] = (
    students_2['credits_completed'] / students_2['years_in_college']
).round(2)
students_2

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,years_in_college,credits_per_year
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,3,24.0
3,S1004,Sofia,Johnson,Computer Science,2nd,20.0,Yes,Spring 2026,3.05,63,Dr. Kim,1,63.0
5,S1006,Liam,Martinez,Statistics,3rd,27.0,Yes,Spring 2024,3.52,45,Dr. Moreno,2,22.5
8,S1009,Emma,Chen,Data Science,3rd,27.0,Yes,Fall 2024,3.07,45,Dr. Moreno,2,22.5
10,S1011,Isabella,Lopez,Statistics,2nd,18.0,Yes,Fall 2024,3.22,54,Dr. Reed,2,27.0
11,S1012,Elijah,Clark,Data Science,4th,26.0,Yes,Fall 2025,3.31,72,Dr. Reed,1,72.0
14,S1015,Mia,Thomas,Statistics,3rd,23.0,Yes,Fall 2024,3.81,36,Dr. Shah,2,18.0
15,S1016,Leo,Moore,Data Science,2nd,25.0,Yes,Spring 2026,3.31,96,Dr. Moreno,1,96.0
17,S1018,Samuel,Hall,Computer Science,4th,27.0,Yes,Fall 2025,3.95,36,Dr. Kim,1,36.0
19,S1020,Daniel,Young,Mathematics,1st,22.0,Yes,Fall 2023,3.75,108,Dr. Shah,3,36.0
20,S1021,Layla,King,Computer Science,2nd,22.0,Yes,Spring 2025,3.83,30,Dr. Shah,1,30.0
23,S1024,Owen,Green,Data Science,2nd,26.0,Yes,Spring 2026,3.73,45,Dr. Kim,1,45.0
24,S1025,Chloe,Baker,Data Science,4th,19.0,Yes,Spring 2024,3.85,84,Dr. Moreno,2,42.0
25,S1026,Isaac,Adams,Statistics,4th,23.0,Yes,Fall 2024,3.29,36,NaN,2,18.0
26,S1027,Elena,Nelson,Computer Science,2nd,27.0,Yes,Fall 2024,3.45,36,Dr. Kim,2,18.0

In [87]:
student_list = [
    f"{row['first_name']} {row['last_name']} ({row['program']})" 
    for index, row in students.iterrows()
]
student_list

['Avery Nguyen (Mathematics)',
 'Maya Patel (Computer Science)',
 'Noah Garcia (Mathematics)',
 'Sofia Johnson (Computer Science)',
 'Ethan Kim (Computer Science)',
 'Liam Martinez (Statistics)',
 'Olivia Brown (Statistics)',
 'Lucas Wilson (Data Science)',
 'Emma Chen (Data Science)',
 'Mateo Davis (Data Science)',
 'Isabella Lopez (Statistics)',
 'Elijah Clark (Data Science)',
 'Amara Taylor (Data Science)',
 'Henry Anderson (Mathematics)',
 'Mia Thomas (Statistics)',
 'Leo Moore (Data Science)',
 'Nora Lewis (Mathematics)',
 'Samuel Hall (Computer Science)',
 'Zoe Allen (Statistics)',
 'Daniel Young (Mathematics)',
 'Layla King (Computer Science)',
 'Julian Wright (Statistics)',
 'Grace Scott (Data Science)',
 'Owen Green (Data Science)',
 'Chloe Baker (Data Science)',
 'Isaac Adams (Statistics)',
 'Elena Nelson (Computer Science)',
 'Caleb Hill (Mathematics)',
 'Aria Campbell (Data Science)',
 'Miles Mitchell (Computer Science)']

For the subset I filtered for students who are currently active and with a gpa at or above 3.00 to isolate students in strong academic standing. For the derived variable I made credits_per_year, which I constructed by parsing the entry year from the entry_term string by calculating their active duration up to 2026 and dividing their total credits_completed by that duration to see on average how many credits they completed each year in school. Lastly I built a list showing each students concatenated full name with the program they're in.

### Part 3 — Joining tables

I expect a one-to-many relationship because an individual student can enroll in multiple courses across different terms.

In [88]:
merge_1 = pd.merge(
    students,
    enrollments,
    on='student_id',
    how='inner',
    validate='one_to_many',
    indicator=True
)

print(merge_1['_merge'].value_counts())
display(merge_1.head())

_merge
both          58
left_only      0
right_only     0
Name: count, dtype: int64

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,advisor,enrollment_id,course_id,term,status,midterm_score,final_score,project_score,attendance_pct,_merge
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,E5001,C102,Spring 2026,Completed,96,65.0,65.0,94.7,both
1,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,E5002,C106,Spring 2026,Completed,81,80.0,63.0,96.6,both
2,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,Dr. Moreno,E5003,C103,Spring 2026,Completed,77,67.0,72.0,88.6,both
3,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,E5004,C106,Fall 2025,Completed,86,NaN,85.0,77.3,both
4,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,Dr. Shah,E5005,C101,Fall 2025,Completed,90,55.0,79.0,85.8,both

I expect a many-to-one relationship because many individual course enrollments map back to an unique course description in the course catalog.

In [89]:
final_merge = pd.merge(
    merged_step1,
    courses,
    on='course_id',
    how='inner',
    validate='many_to_one',
    indicator='_merge_course'
)

print(final_merge['_merge_course'].value_counts())
display(final_merge.head())

_merge_course
both          57
left_only      0
right_only     0
Name: count, dtype: int64

,student_id,first_name,last_name,program,year,age,active,entry_term,gpa,credits_completed,...,project_score,attendance_pct,_merge,department,course_number,course_title,credits,level,delivery,_merge_course
0,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,...,65.0,94.7,both,STA,270,Applied Statistics,3,Undergraduate,Hybrid,both
1,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,...,63.0,96.6,both,STA,556,Statistics and Data Science Computing Workflows,3,Graduate,In Person,both
2,S1001,Avery,Nguyen,Mathematics,1st,27.0,Yes,Fall 2023,3.51,72,...,72.0,88.6,both,CS,126,Introduction to Computing,4,Undergraduate,In Person,both
3,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,...,85.0,77.3,both,STA,556,Statistics and Data Science Computing Workflows,3,Graduate,In Person,both
4,S1002,Maya,Patel,Computer Science,1st,27.0,Yes,Spring 2026,2.71,108,...,79.0,85.8,both,STA,141,Exploratory Data Analysis,3,Undergraduate,In Person,both

When merging students with enrollments, rows for students with multiple class registrations are naturally duplicated across the output table. This occurs because a student's constant attributes like their program has to be repeated alongside every distinct course enrollment entry like their final_score to maintain an analysis ready structure without losing any student context.

### Part 4 — Missing data and reshaping

In [90]:
missing_counts = final_merge.isnull().sum()
missing_percentages = (final_merge.isnull().mean() * 100).round(2)

missing = pd.DataFrame({
    'Missing Count': missing_counts,
    'Missing Percentage (%)': missing_percentages
})
missing

                   Missing Count  Missing Percentage (%)
student_id                     0                    0.00
first_name                     0                    0.00
last_name                      0                    0.00
program                        0                    0.00
year                           0                    0.00
age                            4                    7.02
active                         0                    0.00
entry_term                     0                    0.00
gpa                            4                    7.02
credits_completed              0                    0.00
advisor                        1                    1.75
enrollment_id                  0                    0.00
course_id                      0                    0.00
term                           0                    0.00
status                         0                    0.00
midterm_score                  0                    0.00
final_score                    5                    8.77
project_score                  3                    5.26
attendance_pct                 2                    3.51
_merge                         0                    0.00
department                     0                    0.00
course_number                  0                    0.00
course_title                   0                    0.00
credits                        0                    0.00
level                          0                    0.00
delivery                       0                    0.00
_merge_course                  0                    0.00

In [91]:
rows_missing = final_merge[final_merge['final_score'].isnull()]
len(rows_missing)

5

In [92]:
reshaped_df = pd.melt(
    final_merge,
    id_vars=['student_id', 'course_id'],
    value_vars=['midterm_score', 'final_score', 'project_score'],
    var_name='assessment_type',
    value_name='score'
)
reshaped_df

    student_id course_id assessment_type  score
0        S1001      C102   midterm_score   96.0
1        S1001      C106   midterm_score   81.0
2        S1001      C103   midterm_score   77.0
3        S1002      C106   midterm_score   86.0
4        S1002      C101   midterm_score   90.0
..         ...       ...             ...    ...
166      S1027      C107   project_score   94.0
167      S1028      C107   project_score   88.0
168      S1028      C105   project_score   85.0
169      S1029      C104   project_score   85.0
170      S1029      C108   project_score   78.0

[171 rows x 4 columns]

Automatically replacing every missing value with zero would be inappropriate for this dataset because for performance metrics like final_score, substituting a missing entry with 0 would tank student averages, distort summary statistics, and incorrectly change an unrecorded/missing grade with an absolute academic failure.

### Part 5 — Reproducible submission

In [93]:
final_merge.to_csv('../Data/Processed/final_analysis_dataset.csv', index=False)